### ISSUE TITLE
Import error while fetching the Eradiate data using the CLI

### ISSUE THREAD

**Issue by wint3ria** [eradiate/eradiate#260]
The command `eradiate data fetch` fails on my configuration on ref f51aa9704fb8af256dd64492a3c9a312d10fb7f4 (main, from 25th aug 2022).

Here is the traceback from the CLI:

``` bash
(msp) msp@168a3187bd2e:~$ eradiate data fetch
Reading file list from '/home/msp/sources/eradiate/resources/downloads.yml'
Fetching 'ckd/absorption/1nm/afgl_1986-us_standard-1nm-v3.nc'
Traceback (most recent call last):
  File "/home/msp/.conda/envs/msp/bin/eradiate", line 8, in <module>
    sys.exit(main())
  File "/home/msp/.conda/envs/msp/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/msp/.conda/envs/msp/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/msp/.conda/envs/msp/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/msp/.conda/envs/msp/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/msp/.conda/envs/msp/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/msp/.conda/envs/msp/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/msp/sources/eradiate/src/eradiate/cli.py", line 178, in fetch
    path = eradiate.data._store.data_store.fetch(filename)
  File "/home/msp/sources/eradiate/src/eradiate/util/lazy_loader.py", line 93, in __getattr__
    raise AttributeError(f"module '{package_name}' has no attribute '{name}'")
AttributeError: module 'eradiate.data' has no attribute '_store'

```

The following line seems to be the culprit:

https://github.com/eradiate/eradiate/blob/f51aa9704fb8af256dd64492a3c9a312d10fb7f4/src/eradiate/cli.py#L178

This might be linked to the recent implementation of the lazy loader. I don't have a lot of knowledge on how the lazy loader works in details, but after a bit of investigation, explicitely importing the `_store` submodule should fix the problem. Here is a proposed fix:

``` python
from eradiate.data import _store

[...]

def fetch(files, from_file):

    [...]
    
    for filename in files:
        try:
            console.print(f"[blue]Fetching '{filename}'[/]")
            path = _store.data_store.fetch(filename)
        except DataError:

[...]
```

Could the lazy loader load the submodules in an inline fashion, given some additional work? I have no idea how to do so.

This is low priority on my side, since I already downloaded everything. People may also be able to download the datasets manually, but it's far from being convenient.

**Comment by leroyvn** [comment]
Hi @wint3ria, thank for reporting this. It's actually a stupid mistake on my end: the CLI is written as a piece of "client" code and should therefore not use `eradiate.data._store` since it's private.

The fix is to use `eradiate.data.data_store`, which is public. This is fixed by 5ca95922de94a23d87fc12bd740e246c35487fa7.
