### ISSUE TITLE
[BUG] Quickstart does not work

### ISSUE THREAD

**Issue by seb-absolute-sensing** [eradiate/eradiate#356]
# Bug report

## Summary

To test eradiate I simply tried running the sequence proposed in the Quickstart.
An error occurred when importing the eradiate.scenes module

## Description

The code is very simple:
```python
import eradiate

import numpy as np

import eradiate.scenes as ertsc
from eradiate import unit_registry as ureg
eradiate.set_mode("mono")

if __name__ == "__main__":

    surface_bsdf = ertsc.bsdfs.LambertianBSDF()
    atmosphere = ertsc.atmosphere.MolecularAtmosphere.ussa_1976(has_absorption=False)
    illumination = ertsc.illumination.DirectionalIllumination(
        zenith=15.0, azimuth=0.0
    )
    measure = ertsc.measure.MultiDistantMeasure.hplane(
        id="toa_brf",
        zeniths=np.arange(-75, 76, 5),
        azimuth=0,
        srf={"type": "multi_delta", "wavelengths": 550.0 * ureg.nm},
        spp=10000,
    )

    exp = eradiate.experiments.AtmosphereExperiment(
        surface=surface_bsdf,
        atmosphere=atmosphere,
        illumination=illumination,
        measures=measure,
    )

    results = eradiate.run(exp)
    print(results)
```
When running it I got:
```
Traceback (most recent call last):
  File "/home/seb/miniconda3/envs/gesat_demo/lib/python3.11/enum.py", line 276, in __set_name__
    enum_member = enum_class._value2member_map_[value]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'noinit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seb/projects/gesat_demo/src/gesat/rtm.py", line 7, in <module>
    eradiate.set_mode("mono")
    ^^^^^^^^^^^^^^^^^
  File "/home/seb/miniconda3/envs/gesat_demo/lib/python3.11/site-packages/lazy_loader/__init__.py", line 77, in __getattr__
    submod = importlib.import_module(submod_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seb/miniconda3/envs/gesat_demo/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/seb/miniconda3/envs/gesat_demo/lib/python3.11/site-packages/eradiate/_mode.py", line 9, in <module>
    from .attrs import documented, parse_docs
  File "/home/seb/miniconda3/envs/gesat_demo/lib/python3.11/site-packages/eradiate/attrs.py", line 62, in <module>
    class DocFlags(enum.Flag):
  File "/home/seb/miniconda3/envs/gesat_demo/lib/python3.11/enum.py", line 538, in __new__
    raise exc
  File "/home/seb/miniconda3/envs/gesat_demo/lib/python3.11/enum.py", line 296, in __set_name__
    and _is_single_bit(value)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seb/miniconda3/envs/gesat_demo/lib/python3.11/enum.py", line 98, in _is_single_bit
    num &= num - 1
           ~~~~^~~
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

## Steps to reproduce

When simply running 'eradiate show', the same error occurs 

## System configuration

- Operating system: Ubuntu 22.04 WSL
- Compiler: .gcc
- Python version: ... Python 3.11.0
- Eradiate version: ... 0.23.2

**Comment by seb-absolute-sensing** [comment]
If I replace in eradiate/attrs.py

```python
class DocFlags(enum.Flag):
    """
    Extra flags used to pass information about docs.
    """

    NOINIT = 'noinit'
```

by

```python
class DocFlags(enum.Flag):
    """
    Extra flags used to pass information about docs.
    """

    NOINIT = enum.auto()
```

I can run the code and eradiate show command

**Comment by wint3ria** [comment]
Hello @seb-absolute-sensing ,

I can reproduce this problem with [Python >=3.11](https://docs.python.org/3/whatsnew/3.11.html#enum). The current codebase  runs without any problem on your example with Python ==3.10 an Python ==3.8.

We usually test Eradiate with Python ==3.8. There is no "officially supported" version though.

If you need to use the [Eradiate PyPI package](https://pypi.org/project/eradiate/), I thus suggest that you use Python ==3.8 as a temporary solution.

Otherwise I tested your solution and it indeed removes the exception, and runs on both 3.11 and 3.8. The test suite run on 3.8 at least.

The last point is to check the doc build and the behavior of the `documented` and `parse_docs` functions in both Python versions. I may do that tomorrow

Thank you for reporting this issue

**Comment by leroyvn** [comment]
Thank you for this report @seb-absolute-sensing. #358 should have fixed that and will be available upon with next release (coming very soon!). You can benefit from it now if you run a dev setup. Please don't hesitate to get back in touch with us if this doesn't address your issue.
