### ISSUE TITLE
[BUG] Crash with PyPI package v0.24.2.post1 and xarray 2023.8

### ISSUE THREAD

**Issue by leroyvn** [eradiate/eradiate#367]
# Bug report

## Description

When launching a simulation with the PyPI package, in CKD mode, the code raises a `ValueError`. The stack trace is as follows:

```
Traceback (most recent call last):
  File "/home/leroyv/Documents/src/personal/sandboxes/eradiate-debug/debug_20230914.py", line 39, in <module>
    results = eradiate.run(exp)
              ^^^^^^^^^^^^^^^^^
  File "/home/leroyv/miniforge3/envs/eradiate-debug/lib/python3.11/site-packages/eradiate/experiments/_core.py", line 645, in run
    exp.process(spp=spp, seed_state=seed_state)
  File "/home/leroyv/miniforge3/envs/eradiate-debug/lib/python3.11/site-packages/eradiate/experiments/_core.py", line 449, in process
    self.init()
  File "/home/leroyv/miniforge3/envs/eradiate-debug/lib/python3.11/site-packages/eradiate/experiments/_core.py", line 431, in init
    mi.load_dict(kdict_template.render(ctx=self.context_init)),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leroyv/miniforge3/envs/eradiate-debug/lib/python3.11/site-packages/eradiate/kernel/_kernel_dict.py", line 151, in render
    value = v(ctx) if isinstance(v, InitParameter) else v
            ^^^^^^
  File "/home/leroyv/miniforge3/envs/eradiate-debug/lib/python3.11/site-packages/eradiate/kernel/_kernel_dict.py", line 40, in __call__
    return self.evaluator(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/leroyv/miniforge3/envs/eradiate-debug/lib/python3.11/site-packages/eradiate/scenes/atmosphere/_core.py", line 599, in <lambda>
    self.eval_albedo(ctx.si).m_as(ureg.dimensionless),
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leroyv/miniforge3/envs/eradiate-debug/lib/python3.11/site-packages/eradiate/scenes/atmosphere/_molecular_atmosphere.py", line 254, in eval_albedo
    return self.radprops_profile.eval_albedo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leroyv/miniforge3/envs/eradiate-debug/lib/python3.11/functools.py", line 946, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leroyv/miniforge3/envs/eradiate-debug/lib/python3.11/site-packages/eradiate/radprops/_core.py", line 332, in _
    return self.eval_albedo_ckd(w=si.w, g=si.g, zgrid=zgrid).squeeze()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leroyv/miniforge3/envs/eradiate-debug/lib/python3.11/site-packages/eradiate/radprops/_afgl1986.py", line 152, in eval_albedo_ckd
    sigma_t = self.eval_sigma_t_ckd(w=w, g=g, zgrid=zgrid)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leroyv/miniforge3/envs/eradiate-debug/lib/python3.11/site-packages/eradiate/radprops/_afgl1986.py", line 248, in eval_sigma_t_ckd
    sigma_a = self.eval_sigma_a_ckd(w=w, g=g, zgrid=zgrid)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leroyv/miniforge3/envs/eradiate-debug/lib/python3.11/site-packages/eradiate/radprops/_afgl1986.py", line 178, in eval_sigma_a_ckd
    ds = ds.reindex({"bd": idx})
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leroyv/miniforge3/envs/eradiate-debug/lib/python3.11/site-packages/xarray/core/dataset.py", line 3665, in reindex
    return alignment.reindex(
           ^^^^^^^^^^^^^^^^^^
  File "/home/leroyv/miniforge3/envs/eradiate-debug/lib/python3.11/site-packages/xarray/core/alignment.py", line 890, in reindex
    aligner = Aligner(
              ^^^^^^^^
  File "/home/leroyv/miniforge3/envs/eradiate-debug/lib/python3.11/site-packages/xarray/core/alignment.py", line 162, in __init__
    self.indexes, self.index_vars = self._normalize_indexes(indexes)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leroyv/miniforge3/envs/eradiate-debug/lib/python3.11/site-packages/xarray/core/alignment.py", line 209, in _normalize_indexes
    for idx, index_vars in Indexes(xr_indexes, xr_variables).group_by_index():
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leroyv/miniforge3/envs/eradiate-debug/lib/python3.11/site-packages/xarray/core/indexes.py", line 1435, in __init__
    raise ValueError(
ValueError: unmatched keys found in indexes and variables: {'bin', 'index'}
```

## Steps to reproduce

1. In a fresh environment, install Eradiate from PyPI: `pip install eradiate==0.24.2.post1`. Make sure that xarray 2023.8 is used.
2. Run the reproducer below.

```python
import eradiate
import eradiate.scenes as ertsc
from eradiate import unit_registry as ureg
from eradiate.scenes.atmosphere import MolecularAtmosphere
from eradiate.scenes.spectra import SolarIrradianceSpectrum
from eradiate.spectral import WavelengthSet

eradiate.set_mode("ckd_double")

surface_bsdf = ertsc.bsdfs.LambertianBSDF(reflectance=0.5)
atmosphere = MolecularAtmosphere.afgl_1986(model="us_standard")
irradiance = SolarIrradianceSpectrum(dataset="coddington_2021-0.025_nm")
illumination = ertsc.illumination.DirectionalIllumination(
    zenith=15.0, azimuth=10.0, irradiance=irradiance
)
spectral_range = WavelengthSet.arange(
    400.0 * ureg.nm,
    410.0 * ureg.nm,
    10 * ureg.nm,
)
measure = ertsc.measure.MultiDistantMeasure.hplane(
    id="toa_brf",
    zeniths=10.0,
    azimuth=190.0,
    srf=ertsc.spectra.MultiDeltaSpectrum(wavelengths=spectral_range.wavelengths),
    spp=1000,
)
exp = eradiate.experiments.AtmosphereExperiment(
    default_spectral_set=spectral_range,
    surface=surface_bsdf,
    atmosphere=atmosphere,
    illumination=illumination,
    measures=measure,
)
results = eradiate.run(exp)
```

## System configuration

`eradiate show` output:
```
── System ─────────────────────────────────────────────────────────────────────────────────

CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
OS: Ubuntu 22.04.3 LTS
Python: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]

── Versions ───────────────────────────────────────────────────────────────────────────────

• eradiate 0.24.2.post1
• drjit 0.4.1
• mitsuba 3.2.1
• eradiate-mitsuba 0.0.2

── Available Mitsuba variants ─────────────────────────────────────────────────────────────

• scalar_mono
• scalar_mono_double
• scalar_rgb
• scalar_spectral
• llvm_rgb

── Configuration ──────────────────────────────────────────────────────────────────────────

• ERADIATE_AZIMUTH_CONVENTION: AzimuthConvention.EAST_RIGHT
• ERADIATE_DATA_STORE_URL: http://eradiate.eu/data/store/
• ERADIATE_DOWNLOAD_DIR: 
/home/leroyv/Documents/src/personal/sandboxes/eradiate-debug/.eradiate_downloads
• ERADIATE_OFFLINE: False
• ERADIATE_PROGRESS: 2 (2)
• ERADIATE_SMALL_FILES_REGISTRY_REVISION: master
• ERADIATE_SMALL_FILES_REGISTRY_URL: 
https://raw.githubusercontent.com/eradiate/eradiate-data
• ERADIATE_SOURCE_DIR: None
```

**Comment by leroyvn** [comment]
This issue is fixed by 23f2f14. The patch will be available as part of release v0.24.3.
